### ISSUE TITLE
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by Brottweiler** [miekg/lean#12]
From https://github.com/Eriner/zim/issues/110 since it seems to be an issue with this prompt.

- Current commit: https://github.com/miekg/lean/commit/1b942b452143458308a3b67fbe77f7405a499640

---

When using the lean prompt, and trying to create a new local git repo using `git init`, there is the following error

```sh
% git init
Initialized empty Git repository in /home/brott/Desktop/testgit/.git/
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.                                               
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### Related info

- https://stackoverflow.com/questions/12267912/git-fatal-ambiguous-argument-head-unknown-revision-or-path-not-in-the-workin

**Comment by miekg** [comment]
Inclined to revert that change. But maybe there is a quick fix?

**Comment by miekg** [comment]
reverted those changes.

**Comment by rifaterdemsahin** [comment]
started to use this one https://git-scm.com/docs/git-log/1.7.2

for a work around...instead of shortlog
