### ISSUE TITLE
Small triangle before % in iTerm

### ISSUE THREAD

**Issue by YujiShen** [miekg/lean#17]
There is a small triangle before the "%" when I use iTerm. It is perfect normal when I user Terminal. Is this a problem with the theme or iTerm?
<img width="48" alt="2017-02-02_22-12-34 1" src="https://cloud.githubusercontent.com/assets/4230496/22578171/b9469f9a-e994-11e6-835f-271a23b4d3d3.png">

**Comment by f440** [comment]
The sign is set by [iTerm's shell integration](https://www.iterm2.com/documentation-shell-integration.html).

**Comment by YujiShen** [comment]
@f440 Thanks for pointing it out and the link! 
Disable it under Profile -> Terminal -> Show mark indicators.
