### ISSUE TITLE
some fails when i source the prompt_lean-test.zsh

### ISSUE THREAD

**Issue by lluvio** [miekg/lean#26]
```
% source prompt_lean_test.zsh                                                        ~/code/source/lean$vcs_info_msg_0_
  OK - prompt
FAIL - rprompt
00000000  25 46 7b 79 65 6c 6c 6f  77 7d 25 66 25 46 7b 31  |%F{yellow}%f%F{1|
00000010  34 30 7d 2f 74 6d 70 25  46 7b 32 34 31 7d 24 76  |40}/tmp%F{241}$v|
00000020  63 73 5f 69 6e 66 6f 5f  6d 73 67 5f 30 5f 25 66  |cs_info_msg_0_%f|
00000030  25 66 0a                                          |%f.|
00000033
00000000  25 46 7b 79 65 6c 6c 6f  77 7d 25 66 25 46 7b 31  |%F{yellow}%f%F{1|
00000010  34 30 7d 2f 74 6d 70 25  46 7b 32 34 31 7d 24 76  |40}/tmp%F{241}$v|
00000020  63 73 5f 69 6e 66 6f 5f  6d 73 67 5f 30 5f 20 25  |cs_info_msg_0_ %|
00000030  46 7b 79 65 6c 6c 6f 77  7d 25 6d 25 66 25 66 25  |F{yellow}%m%f%f%|
00000040  66 0a                                             |f.|
00000042
  OK - lean_left
FAIL - lean_right
00000000  25 46 7b 79 65 6c 6c 6f  77 7d 25 66 25 46 7b 31  |%F{yellow}%f%F{1|
00000010  34 30 7d 2f 74 6d 70 25  46 7b 32 34 31 7d 24 76  |40}/tmp%F{241}$v|
00000020  63 73 5f 69 6e 66 6f 5f  6d 73 67 5f 30 5f 25 66  |cs_info_msg_0_%f|
00000030  72 69 67 68 74 25 66 0a                           |right%f.|
00000038
00000000  25 46 7b 79 65 6c 6c 6f  77 7d 25 66 25 46 7b 31  |%F{yellow}%f%F{1|
00000010  34 30 7d 2f 74 6d 70 25  46 7b 32 34 31 7d 24 76  |40}/tmp%F{241}$v|
00000020  63 73 5f 69 6e 66 6f 5f  6d 73 67 5f 30 5f 20 25  |cs_info_msg_0_ %|
00000030  46 7b 79 65 6c 6c 6f 77  7d 25 6d 25 66 25 66 72  |F{yellow}%m%f%fr|
00000040  69 67 68 74 25 66 0a                              |ight%f.|
00000047
  OK - tmux
FAIL - time
00000000  25 46 7b 79 65 6c 6c 6f  77 7d 31 73 20 25 66 25  |%F{yellow}1s %f%|
00000010  46 7b 31 34 30 7d 2f 74  6d 70 25 46 7b 32 34 31  |F{140}/tmp%F{241|
00000020  7d 24 76 63 73 5f 69 6e  66 6f 5f 6d 73 67 5f 30  |}$vcs_info_msg_0|
00000030  5f 25 66 25 66 0a                                 |_%f%f.|
00000036
00000000  25 46 7b 79 65 6c 6c 6f  77 7d 31 73 20 25 66 25  |%F{yellow}1s %f%|
00000010  46 7b 31 34 30 7d 2f 74  6d 70 25 46 7b 32 34 31  |F{140}/tmp%F{241|
00000020  7d 24 76 63 73 5f 69 6e  66 6f 5f 6d 73 67 5f 30  |}$vcs_info_msg_0|
00000030  5f 20 25 46 7b 79 65 6c  6c 6f 77 7d 25 6d 25 66  |_ %F{yellow}%m%f|
00000040  25 66 25 66 0a                                    |%f%f.|
00000045

```

**Comment by miekg** [comment]
Why are you sources prompt_lean_test.zsh ?

**Comment by lluvio** [comment]
@miekg  i am sorry,  i just found the `$vcs_info_msg_0_` not work.... 

![image](https://user-images.githubusercontent.com/6127266/27276516-10539ca4-550e-11e7-80e6-61630421d3f4.png)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/lean] some fails when i ..." ]
>@miekg  i am sorry,  i just found the `$vcs_info_msg_0_` not work....
>
>![image](https://user-images.githubusercontent.com/6127266/27276516-10539ca4-550e-11e7-80e6-61630421d3f4.png)

weird.... Doesn't happen for me... :( Latest git, just checked, shows 'master' 
if I go into a git repo.

/Miek

--
Miek Gieben

**Comment by lluvio** [comment]
append these  head of file. fixed this problem

```
setopt prompt_subst
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/lean] some fails when i ..." ]
>append these  head of file. fixed this problem
>
>```
>setopt prompt_subst
>```

Should this be in the docs?

**Comment by lluvio** [comment]
@miekg  i have found there from book <[From Bash to Z Shell: Conquering the Command Line](https://books.google.com.hk/books?id=_q7ZgTUvft0C&pg=PA150&lpg=PA150&dq=setopt+prompt_subst&source=bl&ots=IiCZrc6O2d&sig=UdAKrznZ88myZtunMKe_GAmk8o0&hl=zh-CN&sa=X&ved=0ahUKEwjRwbusxcnUAhUI4YMKHZ_6D5oQ6AEIaTAJ#v=onepage&q=setopt%20prompt_subst&f=false)>

To be able to include variables and other standard substitutions in your prompts, the option promt_subst has to be turned on.This is not on by default, since very old version of zsh didn’t have the option. It’s probable a good idea just to turn it on.

**Comment by lluvio** [comment]
i think this is needed to add

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/lean] some fails when i ..." ]
>@miekg  i have found there from book <From Bash to Z Shell: Conquering the Command Line>
>
>To be able to include variables and other standard substitutions in your prompts, the option promt_subst has to be turned on.This is not on by default, since very old version of zsh didn’t have the option. It’s probable a good idea just to turn it on.

OK done
