### ISSUE TITLE
new to this; trying to set environment variables?

### ISSUE THREAD

**Issue by dismae** [miekg/lean#27]
Hey there! I'm using lean with zim, and I'm trying to figure out where and how to set the PROMPT_LEAN-prefixed environment variables. 

Also, I don't know if vimode was supposed to automatically be registered, but whenever I enter vimode nothing happens on the prompt. 

For reference, I'm using:
Mac OSX
iTerm2
zsh
tmux

everything else works fine (t shows up when tmux is active, seconds are registered, git shows up).

Thanks for your help!

**Comment by miekg** [comment]
Sorry, don't know anything about zim
