### ISSUE TITLE
Install theme

### ISSUE THREAD

**Issue by Yamakaky** [miekg/lean#3]
Hi.
I'm new at zsh, could you add how to install your theme in the README?

**Comment by miekg** [comment]
Probably won't have any time looking in to this.... Is it possible for you
to check what is needed and raise a PR to improve the docs?

**Comment by Yamakaky** [comment]
where did you put it on you computer?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [lean] Install theme (#3)..." ]

> where did you put it on you computer?

% ls -l ~/.zsh/functions/lean.plugin.zsh                                      ~
-rw-rw-r-- 1 miek miek 3.5K Jan  3 12:08 /home/miek/.zsh/functions/lean.plugin.zsh

With the appropriate fpath :

fpath=($fpath ~/.zsh/functions/Completion ~/.zsh/functions)

**Comment by Yamakaky** [comment]
In fact, sourcing `promt_lean_theme` from zshrc works.

**Comment by DoomHammer** [comment]
#6 may help here a bit :)
