### ISSUE TITLE
Extra text under Emacs ansi-term

### ISSUE THREAD

**Issue by YujiShen** [miekg/lean#34]
Under Emacs (Spacemacs) ansi-term, I will get some extra text before actual result.
For example:
```bash
% cd ~
0;Downloads: cd ~%
% ls
0;Yuji: gls --color=tty Applications Desktop Documents
```
These texts will not show if I enter /bin/bash under ansi-term.

I am not sure what causes this problem... Is lean, or oh-my-zsh or zsh, or emacs?

**Comment by miekg** [comment]
This look  like the xterm title printing. If not,  I dont know; dont use the terminal

**Comment by YujiShen** [comment]
Thanks for the clue! I think that is the title. I found some StackOverflow questions about this, here is one [Shell prompt repeating when using ssh in ansi-term](https://stackoverflow.com/questions/17579662/shell-prompt-repeating-when-using-ssh-in-ansi-term/17598138#17598138), and this one [emacs terminal bash (PS1) prompt duplicated](https://stackoverflow.com/questions/24812345/emacs-terminal-bash-ps1-prompt-duplicated). How can I solve this?

**Comment by YujiShen** [comment]
I removed lean theme and extra text did not show again. So I think the problem is related with theme.

**Comment by YujiShen** [comment]
@miekg I solved this and create a pull request.
