### ISSUE TITLE
change left prompt symbol

### ISSUE THREAD

**Issue by karambaq** [miekg/lean#38]
Hello, great prompt.
How can I change the '%' to another symbol, or two symbols?
Thank you.

**Comment by miekg** [comment]
This should be relatively easy, but you'll need to read a bit of the source.

Don't have time to help you with that.

**Comment by dabrowski-adam** [comment]
@karambaq 
The prompt is set [here](https://github.com/miekg/lean/blob/9159bc03abc065b861753c5de994fcdf25a67089/prompt_lean_setup#L116):
```zsh
PROMPT="$prompt_lean_jobs%F{yellow}${prompt_lean_tmux}%f`$PROMPT_LEAN_LEFT`%f%(?.%F{"$COLOR2"}.%B%F{red})%#%f%b "
```

Specifically `#%` represents the prompt symbol. (See: http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html#Shell-state)

So if you want to change **%** to e.g. **❯** replace `#%` with `%(!.#.❯)`

**Comment by karambaq** [comment]
@dabrowski-adam Thank you!
