### ISSUE TITLE
Black background around the prompt symbol after a failed command

### ISSUE THREAD

**Issue by nicolasreich** [miekg/lean#44]
As you can see on this screenshot, there's a black background around the prompt symbol after a command terminated with a non-0 exit code, while when it's 0 it matches the terminal's background. I don't know if it's intended, but can it be changed somewhere?
![wrong_colours](https://user-images.githubusercontent.com/3635943/45453111-238a5d00-b6e0-11e8-8b21-41c049e55b2a.png)

PS: I really enjoy your theme, thanks for having shared it.

**Comment by miekg** [comment]
you're using it on a white background terminal I see. I personally use a black background, hence that color I guess. In `prompt_lean_precmd()` 
~~~
    PROMPT="$prompt_lean_jobs%F{"$COLOR3"}${prompt_lean_tmux}%f`$PROMPT_LEAN_LEFT`%f%(?.%F{"$COLOR2"}.%B%F{203}%K{234})%#%f%k%b "
~~~
is wrong for you in the `(?.%F{"$COLOR2"}.%B%F{203}%K{234})%#` part

**Comment by nicolasreich** [comment]
It was for the example, I discovered it while trying out themes. Is it possible to make it transparent?

**Comment by miekg** [comment]
Probably

**Comment by nicolasreich** [comment]
Got any pointer on how?

**Comment by mikybars** [comment]
Just dropping the `%K{234}` part works for me
