### ISSUE TITLE
Right side of prompt disappearing on smaller terminals

### ISSUE THREAD

**Issue by mracos** [miekg/lean#45]
Thanks for the awesome prompt, better and lighter than pure! ❤️

So the right side of the prompt disappears when we have smaller screens, I know that this is probably the right behavior but there is a way to make it not happen? 😅 

A ENV variable, or maybe point me things I could do in the code to make this happen?

Thanks again! :smile:

**Comment by miekg** [comment]
Haven't experienced this myself and will not have time to debug. But happy
to merge a PR if find out why this is (bonus points if we can test for it
as well)

**Comment by mracos** [comment]
Just resize the window to a really small size, the right prompt hides.
But I will give it a shot later today, but I don't even know where to begin. 😓

**Comment by lunacookies** [comment]
This is not a feature of lean or pure. It is a part of zsh itself; it hides the right prompt when the cursor gets close to the edge of the right prompt.

**Comment by mracos** [comment]
I see, tks for the info @arzg :heart:

Sorry for keeping this issue open for so long. 😅
