### ISSUE TITLE
Use `typeset -g` for global variables in functions

### ISSUE THREAD

**Issue by rjcoelho** [miekg/lean#54]
See https://github.com/sindresorhus/pure/issues/345

Please use declare -g ( or typeset -g, it's the same) to declaring global variables in functions. So, people who set setopt WARN_CREATE_GLOBAL won't get warning like such:
```
prompt_lean_precmd:19: scalar parameter prompt_lean_vimode created globally in function prompt_lean_precmd                                                              
prompt_lean_cmd_exec_time:4: scalar parameter PROMPT_LEAN_CMD_MAX_EXEC_TIME created globally in function prompt_lean_cmd_exec_time
```

Reproduction steps: Wrote setopt WARN_CREATE_GLOBAL in .zshrc.

**Comment by miekg** [comment]
Can you create a pr? Even better would be to minimize global vars
