### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [miekg/lean#61]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/lean] Please add a license f..." ]
>I'd like to add this to awesome-zsh-plugins, but it doesn't have a license
>file.

A good point. Added a license.
