### ISSUE TITLE
Prompt color is not changed back after exiting a root session which run an unsuccessful command

### ISSUE THREAD

**Issue by fedemp** [miekg/lean#8]
```
% su
# somegarbagehere
```

Prompt is now red. Press Enter and prompt is still red.

```
# exit
%
```

Prompt still red.

```
 % ls
 %
```

Prompt back to blue.

**Comment by fedemp** [comment]
![2016-03-11-113536_289x282_scrot](https://cloud.githubusercontent.com/assets/735314/13705083/f61f7d98-e77d-11e5-84fa-73dc2b489232.png)

**Comment by miekg** [comment]
Yes, might be worth fixing. Send a PR! :)

**Comment by miekg** [comment]
won't fix - sorry.
